### ISSUE TITLE
The wrapping is incorrectly superposed on the next line

### ISSUE THREAD

**Issue by wroyca** [NextFaze/vscode-comment-wrap#5]
This happens with Ctrl+L (select current line) which moves the cursor to the next line. 

```rust
Before:
struct Foo {
    // Lorem ipsum dolor sit amet, quo no tale habemus recusabo. Sale reformidans ius an, cum honestatis quaerendum medioc.
    bar: [u8; 2048]
}

After:
struct Foo {
    // Lorem ipsum dolor sit amet, quo no tale habemus recusabo. Sale reformidans
    // ius an, cum honestatis quaerendum medioc.    bar: [u8; 2048]
}

Expected:
struct Foo {
    // Lorem ipsum dolor sit amet, quo no tale habemus recusabo. Sale reformidans
    // ius an, cum honestatis quaerendum medioc.    
    bar: [u8; 2048]
}
```

**Comment by zbarbuto** [comment]
Hi @wroy-ca 
While you're welcome to submit a PR for fixing this (or I may if I get some time) - I actually ended up finding a more feature-full extension for wrapping comments after publishing this. I suggest you check out [Rewrap](https://marketplace.visualstudio.com/items?itemName=stkb.rewrap) (and I'll update the readme to mention this)
