### ISSUE TITLE
Python Support

### ISSUE THREAD

**Issue by seanturner026** [NextFaze/vscode-comment-wrap#6]
Python support for this would be really really nice. I might have a crack at the implementation as I'm looking for this. But anyways opening an issue since there isn't one yet.

**Comment by zbarbuto** [comment]
Hey @seanturner026 sorry I didn't see this sooner.

As per the note in the readme, I recommend checking out [Rewrap](https://marketplace.visualstudio.com/items?itemName=stkb.rewrap) instead (which I found shortly after making this plugin) that is way more fully-featured and probably supports more languages (though I'm not sure about Python specifically).

**Comment by seanturner026** [comment]
Yep, I actually found rewrap recently! Cheers.
